import Head from 'next/head'
import Image from 'next/image'
import { Content, Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import TopBar from '../components/TopBar'
import NavBar from '../components/NavBar'
import Carsoule from '../components/Carsouel'
import Counts from '../components/Counts'
import About from '../components/About'
import Services from '../components/Services'
import Contact from '../components/Contact'
const inter = Inter({ subsets: ['latin'] })
export default function Home() {
  return (
    <>
      <Head>
        <title>Book Review App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <TopBar />
     <NavBar />
     <Carsoule/>
     <Counts/>
   <About/>
   <Services/>
   <Contact />
    </>
  )
}
